name: Run tests

on: [push,workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12
            3.13

      - name: Install tox
        shell: bash -el {0}
        run: pip install tox

      - name: Test with tox
        shell: bash -el {0}
        run: python -m tox run-parallel